- name: create oai config directory
  file:
    path: /usr/local/etc/oai/freeDiameter
    state: directory

- name: get service route interface name
  shell: ip route | grep 10.0.9.0/24 | grep -oP '(?<=dev\s)\w+'
  register: SERVICE_PRIVATE_INTERFACE

- name: set oai component interfaces
  set_fact:
    SPGWU_INTERNAL_INTERFACE: "{{SERVICE_PRIVATE_INTERFACE.stdout}}"

- name: get service route interface name
  shell: ip route | grep 10.8.1.0/24 | grep -oP '(?<=dev\s)\w+'
  register: SERVICE_PUBLIC_INTERFACE

- name: set oai component interfaces
  set_fact:
    SPGWU_EXTERNAL_INTERFACE: "{{SERVICE_PUBLIC_INTERFACE.stdout}}"

- name: overwrite oai epc configs
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: 'acl.j2', dest: '/usr/local/etc/oai/freeDiameter/acl.conf' }
    - { src: 'spgw.j2', dest: '/usr/local/etc/oai/spgw.conf' }
    - { src: 'spgwu.j2', dest: '/usr/local/etc/oai/spgwu.conf' }
